service: ecommerce-web
provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  timeout: 300
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "eu-west-1"}
  deploymentBucket: ${self:custom.deployment-bucket}
  versionFunctions: false
  logRetentionInDays: 30

  stackTags:
    Component: ${self:service}
    Service: ${self:service}
    BusinessUnit: Ecommerce Web
    CostCenter: Ecommerce Web
    Scheduled: no
    Scope: protected
    Developer: yadisnel

  tags:
    Component: ${self:provider.stackTags.Component}
    Service: ${self:provider.stackTags.Service}
    BusinessUnit: ${self:provider.stackTags.BusinessUnit}
    CostCenter: ${self:provider.stackTags.CostCenter}
    Scheduled: ${self:provider.stackTags.Scheduled}
    Scope: ${self:provider.stackTags.Scope}
    Developer: ${self:provider.stackTags.Developer}