export const routesPaths = {
  baseName:'/',
  products: "/products",
  productsPage: "/product-page/:id",
  cart: "/cart",
  wishList: "/wishlist",
  checkout: "/checkout",
  invoice:"/invoice",
  productsList:"/productslist",
  paymentDetails: "/payment-details",
  orderHistory: "/orderhistory",
  pricing: "/pricing",
  error400:'/error400',
  error401:'/error401',
  error403:'/error403',
  error404:'/error404',
  error500:'/error500',
  error503:'/error503',
  maintenance:'/maintenance',
  callback:'/callback'
}
