/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:0583e31f-6009-444d-b316-a4bb01792b6c",
    "aws_cognito_region": "eu-central-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "ba6ae2e05c16495d909c0d2a2bb70045",
    "aws_mobile_analytics_app_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://nrfmwnuwf5afzdkwh2vb2dn5rm.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wdsgswv4mvekvmjpfmykbutuim"
};


export default awsmobile;
