/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:7a25b8ab-86b5-4563-aaa6-d0bf488aded0",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_WWg0sFH8J",
    "aws_user_pools_web_client_id": "gr1qtmfc0s1jeoahq7hrffb5j",
    "oauth": {},
    "aws_mobile_analytics_app_id": "ba6ae2e05c16495d909c0d2a2bb70045",
    "aws_mobile_analytics_app_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://nrfmwnuwf5afzdkwh2vb2dn5rm.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wdsgswv4mvekvmjpfmykbutuim"
};


export default awsmobile;
